### ISSUE TITLE
Widget Thermomètre et nombres négatifs

### ISSUE THREAD

**Issue by JC38** [Heliospeed/jeedom_widget_v4#1]
Bonjour,

D'abord merci pour le partage. Je découvre la V4 et ça m'aide grandement. 
J'ai cependant un petit souci de cohérence d'affichage avec les températures négatives. Le bloc de chiffres est décalé sous l'image.
![Capture](https://user-images.githubusercontent.com/16527222/91642456-d4a07400-ea2b-11ea-81ba-31054222aee0.PNG)

**Comment by Heliospeed** [comment]
Bonjour,
Je viens de faire la correction, j'ai augmenté la largeur du widget de 10px.
![image](https://user-images.githubusercontent.com/33458266/94836046-cbcc0500-0412-11eb-8e24-33e7718d14d1.png)

**Comment by JC38** [comment]
Merci beaucoup. J'ai vu la seconde issue ouverte par Kenderv. ça serait sympa d'avoir ses images spéciales "grand froid".
