### ISSUE TITLE
Affichage des valeurs 

### ISSUE THREAD

**Issue by Kenderv** [Heliospeed/jeedom_widget_v4#2]
Bonjour,
Je découvre aujourd'hui tes widgets qui correspondent exactement à ce que je cherchais savoir afficher une icône et les valeurs à côté. Cependant, bien qu'ayant coché la case Afficher les statistiques sur les widgets je ne les vois pas sur le widget. J'ai sans doute loupé quelque chose. Peux-tu, stp, m'aider à résoudre ce problème. Merci.

PS Désolé je viens de m'apercevoir que je n'avais pas coché la case Afficher les statistiques dans la commande. Pas de problème tout fonctionne.

**Comment by Kenderv** [comment]
Bonjour,
Puis-je me permettre de modifier ton widget sur MON Jeedom afin de l'appliquer sur des valeurs négatives pour mes congélateurs ? Merci de ta réponse et si elle est positive je pourrais, si tu le souhaite te faire passer les modifs.
Bonne journée

**Comment by Heliospeed** [comment]
Bonjour,
Je viens de voir tes messages seulement aujourd'hui ! Pas de problème, tu peux modifier dans ton Jeedom mes widget. Je l'ai justement mis sur git pour que tout le monde puisse les récupérer et adapter en fonction des ses usages.

Bonne journée

**Comment by Kenderv** [comment]
OK Merci. Je l'ai adapté pour les températures négatives de mes congélateurs en rajoutant en haut des thermomètres une étoile de givre et en modifiant les tranches de valeurs

Cordialement

Bonne jornée

 

De : Heliospeed [mailto:notifications@github.com] 
Envoyé : jeudi 1 octobre 2020 09:55
À : Heliospeed/jeedom_widget_v4
Cc : Kenderv; Author
Objet : Re: [Heliospeed/jeedom_widget_v4] Affichage des valeurs (#2)

 

Bonjour,
Je viens de voir tes messages seulement aujourd'hui ! Pas de problème, tu peux modifier dans ton Jeedom mes widget. Je l'ai justement mis sur git pour que tout le monde puisse les récupérer et adapter en fonction des ses usages.

Bonne journée

**Comment by JC38** [comment]
@Kenderv 
Pourrais-tu poster tes images "givrées", ça serait sympa de ta part ;-)

**Comment by Kenderv** [comment]
Avec plaisir. Ci-joint le html modifié et l'ensemble des icones utilisées. Si tu penses que les modifs apportées au html sont à corriger, n'hésites pas à me le dire (ou à le faire), je ne suis pas un surdoué du codage.

[cmd.info.numeric.InfoThermometer.html.zip](https://github.com/Heliospeed/jeedom_widget_v4/files/5322811/cmd.info.numeric.InfoThermometer.html.zip)
[IconThermometer.zip](https://github.com/Heliospeed/jeedom_widget_v4/files/5322812/IconThermometer.zip)

**Comment by Web-svg** [comment]
Bonjour,
Merci pour ce super Widget, idéal pour la V4 en ce qui me concerne, sauf que...je n'ai pas d'affichage des valeurs et j'ai l'erreur suivante 'XXXXX/index.php?v=d&p=dashboard&object_id=7 line 2 > injectedScript - Message: TypeError: widget is null' Ligne : 39
J'ai tout chargé cf la doc via Jeexplorer, pas de soucis particulier, j'ai checké via ssh que les droits étaient bons....
C'est la version de ce matin. J'ai loupé un truc ?
Cordialement

**Comment by Heliospeed** [comment]
> Bonjour,
> Merci pour ce super Widget, idéal pour la V4 en ce qui me concerne, sauf que...je n'ai pas d'affichage des valeurs et j'ai l'erreur suivante 'XXXXX/index.php?v=d&p=dashboard&object_id=7 line 2 > injectedScript - Message: TypeError: widget is null' Ligne : 39
> J'ai tout chargé cf la doc via Jeexplorer, pas de soucis particulier, j'ai checké via ssh que les droits étaient bons....
> C'est la version de ce matin. J'ai loupé un truc ?
> Cordialement

Bonjour,
Qu'elle est la version du widget qui vous pose problème ? Vous utilisez quelle version de Jeedom ?
Cordialement

**Comment by Web-svg** [comment]
> > Bonjour,
> > Merci pour ce super Widget, idéal pour la V4 en ce qui me concerne, sauf que...je n'ai pas d'affichage des valeurs et j'ai l'erreur suivante 'XXXXX/index.php?v=d&p=dashboard&object_id=7 line 2 > injectedScript - Message: TypeError: widget is null' Ligne : 39
> > J'ai tout chargé cf la doc via Jeexplorer, pas de soucis particulier, j'ai checké via ssh que les droits étaient bons....
> > C'est la version de ce matin. J'ai loupé un truc ?
> > Cordialement
> 
> Bonjour,
> Qu'elle est la version du widget qui vous pose problème ? Vous utilisez quelle version de Jeedom ?
> Cordialement

Bonsoir,
J'ai téléchargé le zip de la branche master. La version de Jeedom est passée entretemps de 4.1.18 à 4.1.19.
Je suis sur une Debian Buster (pas Raspberry)
Je dois reconnaitre que je rame un peu pour mettre à jour/recréer les Widgets tels qu'ils étaient en V3.
Hope this help

**Comment by Web-svg** [comment]
PS: Le widget concerné ici est celui dédié aux têtes Danfoss Living Connect

**Comment by Heliospeed** [comment]
Bonsoir,
Pour le moment le widget est bien compatible avec la dernière version 4.1.19 et même la prochaine 4.2.1 (en test)

Il faut bien vérifier les points suivants :

- la source (fichier html) est bien dans le répertoire dashboard :
![image](https://user-images.githubusercontent.com/33458266/106798641-89cffb80-665e-11eb-8c3a-8ca11aae8c24.png)

- les images sont dans le répertoire dashboard/cmd.action.slider.danfossLivingConnect
![image](https://user-images.githubusercontent.com/33458266/106798834-d1568780-665e-11eb-8c41-ca07a221df6b.png)

- Les commandes de l'objet sont bien dans cet ordre et sont bien cochées "Afficher" :
![image](https://user-images.githubusercontent.com/33458266/106799606-bf291900-665f-11eb-863f-cfe87c233cb4.png)

- Les commandes 1,2 et 3 ont bien le widget " Défaut" de paramétrés avec l'option "Afficher le nom" :
![image](https://user-images.githubusercontent.com/33458266/106799813-fb5c7980-665f-11eb-805a-0f1b2f015291.png)

- La commande 4 doit être la seul ou l'on applique le widget danfoss :
![image](https://user-images.githubusercontent.com/33458266/106799943-247d0a00-6660-11eb-89c9-7a423e204c33.png)

Normalement avec tous ces éléments, le widget devrait s'afficher correctement.
Si ça ne fonctionne toujours pas, je vous invite a venir échanger ce problème sur le community jeedom, il y a une bonne communauté qui aura peut être des idées pour trouver la solution plus rapidement : https://community.jeedom.com/t/partage-danfoss-living-connect-widget/

Bonne soirée

**Comment by Web-svg** [comment]
Bonjour,
C'est réglé...une image et les fonts n'étaient pas/plus au bon endroit *<^;)
Nickel
Merci
